DESCRIPTIONS = {
    'book': {
        'data': "{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if notes %}. – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if fingerprint %}. – Фингерпринт: {{ fingerprint }}{% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}",
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        ''',
    },
    'editedbook': { 
        'data': "{{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {% if organization %} {{ organization }} ;{% endif %} {{ editor }}{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if notes %}. – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if fingerprint %}. – Фингерпринт: {{ fingerprint }}{% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}"
    },
    'electronicbook': { 
        'data': '{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %} – URL: {{ url }} (дата обращения: {{ date }}){% if access_mode %}. – Режим доступа: {{ access_mode }}{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if notes %}. – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if fingerprint %}. – Фингерпринт: {{ fingerprint }}{% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
    'chapter': { 
        'data': '{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – {{ section }}. – С. {{ pages }}.{% if notes %} – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if fingerprint %}. – Фингерпринт: {{ fingerprint }}{% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ surname_chapter }} {{ initials_chapter }} {{ section_title }} / {{ initials_chapter }} {{ surname_chapter }} // {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ surname_chapter }} {{ initials_chapter }} {{ section_title }} / {{ initials_chapter }} {{ surname_chapter }} // {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname_chapter }} {{ initials_chapter }} {{ section_title }} / {{ initials_chapter }} {{ surname_chapter }} // {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname_chapter }} {{ initials_chapter }} {{ section_title }} / {{ initials_chapter }} {{ surname_chapter }} // {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}
                        {% else %}
                            {{ surname_chapter }} {{ initials_chapter }} {{ section_title }} / {{ initials_chapter }} {{ surname_chapter }} // {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
    'multivolume': { 
        'data': '{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if notes %}. – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if fingerprint %}. – Фингерпринт: {{ fingerprint }}{% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} ',
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} : [в {{ chapters }} томах] / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} : [в {{ chapters }} томах] / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} : [в {{ chapters }} томах] / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} : [в {{ chapters }} томах] / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} : [в {{ chapters }} томах] / {{ initials }} {{ surname }}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
    'volume': { 
        'data': '{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if notes %}. – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if fingerprint %}. – Фингерпринт: {{ fingerprint }}{% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %} 
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %}. В {{ chapters }} т. Т. {{ n_volume }} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}
            {% else %} 
                {% if second_surname_4 or second_initials_4 %} 
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %}. В {{ chapters }} т. Т. {{ n_volume }} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %}. В {{ chapters }} т. Т. {{ n_volume }} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}
                    {% else %} 
                        {% if second_surname or second_initials %} 
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %}. В {{ chapters }} т. Т. {{ n_volume }} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}
                        {% else %} 
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %}. В {{ chapters }} т. Т. {{ n_volume }} / {{ initials }} {{ surname }}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
    'magazinearticle': { # !!!
        'data': '{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if issn %} – ISSN {{ issn }}{% endif %}{% if doi %} – DOI {{ doi }}{% endif %}{% if key_title %} = {{ key_title }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }} // {{ journal_title }}. – {{ year }}. –{% if volume_n %} Т. {{ volume_n }},{% endif %} № {{ issue }}. – С. {{ pages }}.{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.] // {{ journal_title }}. – {{ year }}. –{% if volume_n %} Т. {{ volume_n }},{% endif %} № {{ issue }}. – С. {{ pages }}.{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }} // {{ journal_title }}. – {{ year }}. –{% if volume_n %} Т. {{ volume_n }},{% endif %} № {{ issue }}. – С. {{ pages }}.{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }} // {{ journal_title }}. – {{ year }}. –{% if volume_n %} Т. {{ volume_n }},{% endif %} № {{ issue }}. – С. {{ pages }}.{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }} // {{ journal_title }}. – {{ year }}. –{% if volume_n %} Т. {{ volume_n }},{% endif %} № {{ issue }}. – С. {{ pages }}.{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %} 
        ''' 
    },
    'newspaperarticle': { 
        'data': '{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if issn %} – ISSN {{ issn }}{% endif %}{% if doi %} – DOI {{ doi }}{% endif %}{% if key_title %} = {{ key_title }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if availability %} : {{ availability }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
     'collectionarticle': {
        'data': '{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }}{% if publishing %} : {{ publishing }}{% endif %}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – С. {{ pages }}.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if notes %}. – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if fingerprint %}. – Фингерпринт: {{ fingerprint }}{% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }} // {{ collection_title }} 
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.] // {{ collection_title }} 
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }} // {{ collection_title }} 
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }} // {{ collection_title }} 
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }} // {{ collection_title }} 
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
    'site': { 
        'data': '{{ title }}{% if title_info %} : {{ title_info }}{% endif %} :{% if site_type %} {{ site_type }}{% endif %} сайт{% if explanations %} : [{{ explanations }}]{% endif %}.{% if place or year %} – {% if place %}{{ place }}{% endif %}{% if place and year %},{% endif %}{% if year %} {{ year }}{% endif %}.{% endif %} – URL: {{ url }} (дата обращения: {{ date }}){% if availability %}. – Режим доступа: {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
    },
    'localaccess': { 
        'data': '{{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %}{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}. – {{ place }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}.{% if physical_characteristics %} – {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if source %} – {{ source }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
    },
    'internetportal': { 
        'data': '{{ title }}{% if title_info %} : {{ title_info }}{% endif %} :{% if site_type %} {{ site_type }}{% endif %} портал{% if explanations %} : [{{ explanations }}]{% endif %}{% if responsibility %} / {{ responsibility }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if access_means %} : {{ access_means }}{% endif %}.{% if place or year %} – {% if place %}{{ place }}{% endif %}{% if place and year %},{% endif %}{% if year %} {{ year }}{% endif %}.{% endif %} – URL: {{ url }} (дата обращения: {{ date }}){% if availability %}. – Режим доступа: {{ availability }}{% endif %}',
    },
    'electronicjournal': { 
        'data': '{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if issn %} – ISSN {{ issn }}{% endif %}{% if doi %} – DOI {{ doi }}{% endif %}{% if key_title %} = {{ key_title }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if availability %} : {{ availability }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }} : электронный журнал. – URL: {{ url }}{% if publication_date %}. – Дата публикации: {{ publication_date }}.{% else %} (дата обращения: {date_today}).{% endif %}{% if date %} (дата обращения: {{ date }}){% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }} : электронный журнал. – URL: {{ url }}{% if publication_date %}. – Дата публикации: {{ publication_date }}.{% else %} (дата обращения: {date_today}).{% endif %}{% if date %} (дата обращения: {{ date }}){% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }} : электронный журнал. – URL: {{ url }}{% if publication_date %}. – Дата публикации: {{ publication_date }}.{% else %} (дата обращения: {date_today}).{% endif %}{% if date %} (дата обращения: {{ date }}){% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }} : электронный журнал. – URL: {{ url }}{% if publication_date %}. – Дата публикации: {{ publication_date }}.{% else %} (дата обращения: {date_today}).{% endif %}{% if date %} (дата обращения: {{ date }}){% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }} : электронный журнал. – URL: {{ url }}{% if publication_date %}. – Дата публикации: {{ publication_date }}. {% else %} (дата обращения: {date_today}).{% endif %}{% if date %} (дата обращения: {{ date }}){% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
    'electronicnewspaper': { 
        'data': '{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if issn %} – ISSN {{ issn }}{% endif %}{% if doi %} – DOI {{ doi }}{% endif %}{% if key_title %} = {{ key_title }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if availability %} : {{ availability }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}{% endif %}. – {{ date }}. – URL: {{ url }} (дата обращения: {{ application_date }}).{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}. – URL: {{ url }} (дата обращения: {{ application_date }}).{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}. – URL: {{ url }} (дата обращения: {{ application_date }}).{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}. – URL: {{ url }} (дата обращения: {{ application_date }}).{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %} // {{ journal_title }}{% if year %}. – {{ year }}{% endif %}{% if issue %}. – № {{ issue }}{% endif %}{% if pages %}. – С. {{ pages }}.{% endif %}{% if date %}. – {{ date }}{% endif %}. – URL: {{ url }} (дата обращения: {{ application_date }}).{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
    'gost': { 
        'data': '{{ title }}{% if introduction %} : {{ introduction }}{% endif %} : дата введения {{ date }}{% if explanations %} : [{{ explanations }}]{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}. – {{ pages }} с.{% if content %} – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
    },
    'dissertation': { 
        'data': '{{ surname }}, {{ initials }} {{ title }} {% if explanations %} : [{{ explanations }}]{% endif %} : специальность {{ speciality }} : диссертация на соискание {{ competition }} / {{ surname }} {{ full_name }}{% if organization %} ; {{ organization }}{% endif %}. – {{ place }}, {{ year }}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if bibliography %}. – Библиогр.: с. {{ bibliography }}.{% endif %}{% if content %} – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
    },
    'dissertationabstract': { 
        'data': '{{ surname }}, {{ initials }} {{ title }} {% if explanations %} : [{{ explanations }}]{% endif %} : специальность {{ speciality }} : автореферат диссертации на соискание {{ competition }} / {{ surname }} {{ full_name }}{% if organization %} ; {{ organization }}{% endif %}. – {{ place }}, {{ year }}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if bibliography %} – Библиогр.: с. {{ bibliography }}.{% endif %}{% if protection %} – Место защиты: {{ protection }}{% endif %}{% if content %} – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
    },
    'manual': { 
        'data': '{% if responsibility %} ; {{ responsibility }}{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if notes %}. – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if bibliography %} – Библиогр.: с. {{ bibliography }}.{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if additional_information %} ({{ additional_information }}){% endif %}{% if fingerprint %}. – Фингерпринт: {{ fingerprint }}{% endif %}{% if availability %} : {{ availability }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
        'authors': '''
            {% if fourth_surname or fourth_initials %}}
                {{ title }}{% if parallel %} = {{ parallel }}{% endif %} : {{ manual_type }} пособие{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_3 }} {{ second_surname_3 }}, {{ third_initials_2 }} {{ third_surname_2 }}, {{ fourth_initials }} {{ fourth_surname }}
            {% else %}
                {% if second_surname_4 or second_initials_4 %}
                    {{ title }}{% if parallel %} = {{ parallel }}{% endif %} : {{ manual_type }} пособие{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_4 }} {{ second_surname_4 }}, {{ third_initials_3 }} {{ third_surname_3 }} [и др.]
                {% else %}
                    {% if second_surname_2 or second_initials_2 %}
                        {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %} : {{ manual_type }} пособие{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials_2 }} {{ second_surname_2 }}, {{ third_initials }} {{ third_surname }}
                    {% else %}
                        {% if second_surname or second_initials %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %} : {{ manual_type }} пособие{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}, {{ second_initials }} {{ second_surname }}
                        {% else %}
                            {{ surname }}, {{ initials }} {{ title }}{% if parallel %} = {{ parallel }}{% endif %} : {{ manual_type }} пособие{% if explanations %} : [{{ explanations }}]{% endif %} / {{ initials }} {{ surname }}
                        {% endif %}
                    {% endif %}
                {% endif %}
            {% endif %}
        '''
    },
    'law': { 
        'data': '{{ title }} : {{ organization }} // {{ place }}. – {{ year }}. –  № {{ publishing }}. – Ст. {{ pages }}.',
    },
    'rule': {
        'data': '{{ title }}{% if parallel %} = {{ parallel }}{% endif %}{% if type_doc %} : {{ type_doc }}{% endif %}{% if explanations %} : [{{ explanations }}]{% endif %}{% if edit_info %}. – {{ edit_info }}{% endif %}{% if par_edit_info %} = {{ par_edit_info }}{% endif %}{% if liability %} / {{ liability }}{% endif %}. – {{ place }} : {{ publishing }}, {{ year }}{% if place_of_distribution %} ; {{ place_of_distribution }}{% endif %}{% if organization_of_distribution %} : {{ organization_of_distribution }} [распространитель],{% endif %}{% if distribution_date %} {{ distribution_date }}{% endif %}{% if manufacture %} ({{ manufacture }}){% endif %}. – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if main_title %} ({{ main_title }}{% if parallel_series_title %} = {{ parallel_series_title }}{% endif %}{% if series_title_information %} : {{ series_title_information }}{% endif %}{% if responsibility_info %} / {{ responsibility_info }}{% endif %}{% if number %}, {{ number }}{% endif %}{% if serial_number %} ; {{ serial_number }}{% endif %}{% if sub_main_title %}. {{ sub_main_title }}{% endif %}{% if sub_parallel_series_title %} = {{ sub_parallel_series_title }}{% endif %}{% if sub_series_title_information %} : {{ sub_series_title_information }}{% endif %}{% if sub_responsibility_info %} / {{ sub_responsibility_info }}{% endif %}{% if sub_number %}, {{ sub_number }}{% endif %}{% if sub_serial_number %} ; {{ sub_serial_number }}{% endif %}){% endif %}{% if notes %}. – {{ notes }}{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if isbn %} – ISBN {{ isbn }}{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
    },
    'patent': { 
        'data': 'Патент № {{ info }}. {{ title }}{% if explanations %} : [{{ explanations }}]{% endif %} : № {{ number }} : заявл. {{ application }} : опубл. {{ publication }} / {{ author }}{% if responsibility %} ; {{ responsibility }}.{% endif %} – {{ pages }}{% if unnumbered_pages %}, [{{ unnumbered_pages }}]{% endif %} с.{% if illustrations %}, {{ illustrations }}{% endif %}{% if physical_characteristics %} : {{ physical_characteristics }}{% endif %}{% if size %} ; {{ size }} см{% endif %}{% if general_notes %}. – {{ general_notes }}{% endif %}{% if accompanying %} + {{ accompanying }}{% endif %}{% if content %}. – {{ content }}{% endif %}{% if content_type %} ({{ content_type }}){% endif %}{% if access_means %} : {{ access_means }}{% endif %}',
    },
    'sitearticle': { 
        'data': '{{ title }} // {{ site_title }} : сайт. – URL: {{ url }} (дата обращения: {{ date }})',
    }
}