from .models import *
from django.forms import ModelForm, TextInput
from django import forms

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        widgets = {"surname": TextInput(attrs={'placeholder': 'Пушкин', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'А. С.', 'class': 'required'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Лермонтов', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'М. Ю.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "title": TextInput(attrs={'placeholder': 'Избранные стихотворения', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Эксмо', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '250', 'class': 'required'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-84213-011-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Selected poems', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'сборник стихотворений', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'иллюстрации А. О. Никоненко', 'class': 'optional'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '18', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': '1 плакат', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Золотая серия поэзии', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Golden poetry series', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные произведения', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Петрова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISBN 978-5-7310-3503-3', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'т. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'произведения А. С. Пушкина', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Иванова', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISBN 978-5-699-12014-7', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'ч. 2', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '5 000 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "fingerprint": TextInput(attrs={'placeholder': 'one, r.co p-e, Suno 3 1623R', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'сборник произведений', 'class': 'optional', 'type': 'hidden'}),
                   'list_id': forms.TextInput(attrs={'type': 'hidden'}),
                   'pub_date': forms.TextInput(attrs={'type': 'hidden'})}


class EditedBookForm(ModelForm):
    class Meta:
        model = EditedBook
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Избранные стихотворения', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Эксмо', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '250', 'class': 'required'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-84213-011-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Selected poems', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'сборник стихотворений', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'иллюстрации А. О. Никоненко', 'class': 'optional'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '18', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': '1 плакат', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Золотая серия поэзии', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Golden poetry series', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные произведения', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Петрова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISBN 978-5-7310-3503-3', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'т. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'произведения А. С. Пушкина', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Иванова', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISBN 978-5-699-12014-7', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'ч. 2', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '5 000 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "fingerprint": TextInput(attrs={'placeholder': 'one, r.co p-e, Suno 3 1623R', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "editor": TextInput(attrs={'placeholder': 'под ред. Н. К. Смирновой, Ф. С. Круглова', 'class': 'required'}),
                   "organization": TextInput(attrs={'placeholder': 'Российская академия наук, Институт мировой литературы им. А.М. Горького', 'class': 'required'}),
                   "explanations": TextInput(attrs={'placeholder': 'сборник произведений', 'class': 'optional', 'type': 'hidden'})}


class ElectronicBookForm(ModelForm):
    class Meta:
        model = ElectronicBook
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Избранные стихотворения', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Пушкин', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'А. С.', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Эксмо', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '250', 'class': 'required'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-84213-011-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Selected poems', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'сборник стихотворений', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'иллюстрации А. О. Никоненко', 'class': 'optional'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "url": TextInput(attrs={'placeholder': 'https://e.lanbook.com/book/110904', 'class': 'required'}),
                   "date": TextInput(attrs={'placeholder': '15.05.2020', 'class': 'required'}),
                   "access_mode": TextInput(attrs={'placeholder': 'для авторизир. пользователей', 'class': 'required'}),
                   "main_title": TextInput(attrs={'placeholder': 'Золотая серия поэзии', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Golden poetry series', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные произведения', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Петрова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISBN 978-5-7310-3503-3', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'т. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'произведения А. С. Пушкина', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Иванова', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISBN 978-5-699-12014-7', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'ч. 2', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '5 000 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "fingerprint": TextInput(attrs={'placeholder': 'one, r.co p-e, Suno 3 1623R', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Лермонтов', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'М. Ю.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'сборник произведений', 'class': 'optional', 'type': 'hidden'})}


class ChapterForm(ModelForm):
    class Meta:
        model = Chapter
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Анализ поэзии А. С. Пушкина', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Иванов', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'С. С.', 'class': 'required'}),
                   "surname_chapter": TextInput(attrs={'placeholder': 'Петрова', 'class': 'required'}),
                   "initials_chapter": TextInput(attrs={'placeholder': 'А. Н.', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Эксмо', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '50-57', 'class': 'required'}),
                   "section": TextInput(attrs={'placeholder': 'Гл. 10', 'class': 'required'}),
                   "section_title": TextInput(attrs={'placeholder': 'Особенности поэзии', 'class': 'required'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-84213-011-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Selected poems', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'сборник', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'иллюстрации А. О. Никоненко', 'class': 'optional'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '5 000 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "fingerprint": TextInput(attrs={'placeholder': 'one, r.co p-e, Suno 3 1623R', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Щербаков', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'И. Л.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'сборник произведений', 'class': 'optional', 'type': 'hidden'})}


class MultivolumeForm(ModelForm):
    class Meta:
        model = Multivolume
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Избранные стихотворения', 'class': 'required'}),
                   "chapters": TextInput(attrs={'placeholder': '2', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Пушкин', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'А. С.', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Эксмо', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '250', 'class': 'required'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-84213-011-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Selected poems', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'сборник стихотворений', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'иллюстрации А. О. Никоненко', 'class': 'optional'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '18', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': '1 плакат', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Золотая серия поэзии', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Golden poetry series', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные произведения', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Петрова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISBN 978-5-7310-3503-3', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'т. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'произведения А. С. Пушкина', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Иванова', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISBN 978-5-699-12014-7', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'ч. 2', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '5 000 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "fingerprint": TextInput(attrs={'placeholder': 'one, r.co p-e, Suno 3 1623R', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Лермонтов', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'М. Ю.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'сборник произведений', 'class': 'optional', 'type': 'hidden'})}


class VolumeForm(ModelForm):
    class Meta:
        model = Volume
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Избранные стихотворения', 'class': 'required'}),
                   "chapters": TextInput(attrs={'placeholder': '2', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Пушкин', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'А. С.', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Эксмо', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '250', 'class': 'required'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-84213-011-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Selected poems', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'сборник стихотворений', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'иллюстрации А. О. Никоненко', 'class': 'optional'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '18', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': '1 плакат', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Золотая серия поэзии', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Golden poetry series', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные произведения', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Петрова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISBN 978-5-7310-3503-3', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'т. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'произведения А. С. Пушкина', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Иванова', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISBN 978-5-699-12014-7', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'ч. 2', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '5 000 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "fingerprint": TextInput(attrs={'placeholder': 'one, r.co p-e, Suno 3 1623R', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Лермонтов', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'М. Ю.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Толстой', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'Л. Н.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Достоевский', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. М.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'сборник произведений', 'class': 'optional'}),
                   "n_volume": TextInput(attrs={'placeholder': '1', 'class': 'required'})}


class MagazineArticleForm(ModelForm):
    class Meta:
        model = MagazineArticle
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Главные фотографии года', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Петров', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'П. Н.', 'class': 'required'}),
                   "journal_title": TextInput(attrs={'placeholder': 'Фотографы России', 'class': 'required'}),
                   "issue": TextInput(attrs={'placeholder': '11', 'class': 'required'}),
                   "volume_n": TextInput(attrs={'placeholder': '2', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '15-23', 'class': 'required'}),
                   "issn": TextInput(attrs={'placeholder': '1563-0102', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Top photos of the year', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '18', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Фотография как искусство', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Photography as art', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные фотографы', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Иванова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISSN 0557-6733', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'вып. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'фотографы Севера', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Никитина', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISSN 0202-2400', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'вып. 2', 'class': 'optional'}),
                   "doi": TextInput(attrs={'placeholder': '10.1596/978-0-8213-6475-8', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "key_title": TextInput(attrs={'placeholder': 'Фотография', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Щербаков', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'И. Л.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'текст', 'class': 'optional', 'type': 'hidden'})}


class NewspaperArticleForm(ModelForm):
    class Meta:
        model = NewspaperArticle
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Главные фотографии года', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Петров', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'П. Н.', 'class': 'required'}),
                   "journal_title": TextInput(attrs={'placeholder': 'Фотографы России', 'class': 'required'}),
                   "issue": TextInput(attrs={'placeholder': '12', 'class': 'required'}),
                   "date": TextInput(attrs={'placeholder': '20 дек.', 'class': 'required'}),
                   "year":  TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '15-17', 'class': 'required'}),
                   "issn": TextInput(attrs={'placeholder': '1563-0102', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-84213-011-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Top photos of the year', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '18', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Фотография как искусство', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Photography as art', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные фотографы', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Иванова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISSN 0557-6733', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'вып. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'фотографы Севера', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Никитина', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISSN 0202-2400', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'вып. 2', 'class': 'optional'}),
                   "doi": TextInput(attrs={'placeholder': '10.1596/978-0-8213-6475-8', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "key_title": TextInput(attrs={'placeholder': 'Фотография', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Щербаков', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'И. Л.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'текст', 'class': 'optional', 'type': 'hidden'})}


class CollectionArticleForm(ModelForm):
    class Meta:
        model = CollectionArticle
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Культура якутов', 'class': 'required'}),
                   "collection_title": TextInput(attrs={'placeholder': 'Современные этнические процессы', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Петров', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'В. А.', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Эксмо', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '30-41', 'class': 'required'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-84213-011-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Yakut culture', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'сборник стихотворений', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'иллюстрации А. О. Никоненко', 'class': 'optional'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '18', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': '1 плакат', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Народы России', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Peoples of Russia', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные исследования', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Петрова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISBN 978-5-7310-3503-3', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'т. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'этнические исследования', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Иванова', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISBN 978-5-699-12014-7', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'ч. 2', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '5 000 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "fingerprint": TextInput(attrs={'placeholder': 'one, r.co p-e, Suno 3 1623R', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Щербаков', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'И. Л.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'текст', 'class': 'optional', 'type': 'hidden'})}


class SiteForm(ModelForm):
    class Meta:
        model = Site
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Google', 'class': 'required'}),
                   "title_info": TextInput(attrs={'placeholder': 'поисковая система', 'class': 'optional'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'optional'}),
                   "year": TextInput(attrs={'placeholder': '1999', 'class': 'optional'}),
                   "url": TextInput(attrs={'placeholder': 'https://google.com', 'class': 'required'}),
                   "date": TextInput(attrs={'placeholder': '25.04.2021', 'class': 'required'}),
                   "update": TextInput(attrs={'placeholder': 'Обновляется в течение суток', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'сайт', 'class': 'optional'}),
                   "site_type": TextInput(attrs={'placeholder': 'официальный', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'для зарегистрир. пользователей', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'электронный', 'class': 'optional', 'type': 'hidden'})}


class LocalAccessForm(ModelForm):
    class Meta:
        model = LocalAccess
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'База данных ППР', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "edit_info": TextInput(attrs={'placeholder': ' Электрон. дан. и прогр.', 'class': 'optional'}),
                   "source": TextInput(attrs={'placeholder': 'Загл. с этикетки видеодиска', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Database', 'class': 'optional'}),
                   "system_requirements": TextInput(attrs={'placeholder': 'ПК 486 или выше ; 8 Mb ОЗУ ; Windows 3.1 или Windows95', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'база данных "Промышленная продукция России"', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'под ред. А. О. Никоненко', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': '1 электрон. опт. диск CD-ROM', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '18', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': 'рук. пользователя (1 л.)', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "fingerprint": TextInput(attrs={'placeholder': 'one, r.co p-e, Suno 3 1623R', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'электронный', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'электронный ресурс', 'class': 'optional', 'type': 'hidden'})}


class InternetPortalForm(ModelForm):
    class Meta:
        model = InternetPortal
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Экономика. Социология. Менеджмент', 'class': 'required'}),
                   "title_info": TextInput(attrs={'placeholder': 'образовательный ресурс', 'class': 'optional'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2003', 'class': 'required'}),
                   "url": TextInput(attrs={'placeholder': 'http://ecsocman.hse.ru/', 'class': 'required'}),
                   "date": TextInput(attrs={'placeholder': '25.04.2021', 'class': 'required'}),
                   "responsibility": TextInput(attrs={'placeholder': 'Высшая школа экономики', 'class': 'optional'}),
                   "update": TextInput(attrs={'placeholder': 'Обновляется в течение суток', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'сайт', 'class': 'optional'}),
                   "site_type": TextInput(attrs={'placeholder': 'федеральный образовательный', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'для зарегистрир. пользователей', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'электронный', 'class': 'optional', 'type': 'hidden'})}


class ElectronicJournalForm(ModelForm):
    class Meta:
        model = ElectronicJournal
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Главные фотографии года', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Петров', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'П. Н.', 'class': 'required'}),
                   "journal_title": TextInput(attrs={'placeholder': 'Фотографы России', 'class': 'required'}),
                   "issn": TextInput(attrs={'placeholder': '1563-0102', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Top photos of the year', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Фотография как искусство', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Photography as art', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные фотографы', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Иванова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISSN 0557-6733', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'вып. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'фотографы Севера', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Никитина', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISSN 0202-2400', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'вып. 2', 'class': 'optional'}),
                   "doi": TextInput(attrs={'placeholder': '10.1596/978-0-8213-6475-8', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "key_title": TextInput(attrs={'placeholder': 'Фотография', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Щербаков', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'И. Л.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'текст', 'class': 'optional'}),
                   "url": TextInput(attrs={'placeholder': 'http://www.photographers.ru/journal/', 'class': 'required'}),
                   "publication_date": TextInput(attrs={'placeholder': '19.06.2021', 'class': 'required'}),
                   "date": TextInput(attrs={'placeholder': '25.04.2021'})}


class ElectronicNewspaperForm(ModelForm):
    class Meta:
        model = ElectronicNewspaper
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Главные фотографии года', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Петров', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'П. Н.', 'class': 'required'}),
                   "journal_title": TextInput(attrs={'placeholder': 'Фотографы России', 'class': 'required'}),
                   "issue": TextInput(attrs={'placeholder': '12', 'class': 'required'}),
                   "date": TextInput(attrs={'placeholder': '20 дек', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2020', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '15-17', 'class': 'required'}),
                   "issn": TextInput(attrs={'placeholder': '1563-0102', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Top photos of the year', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Фотография как искусство', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Photography as art', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'избранные фотографы', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Иванова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISSN 0557-6733', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'вып. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'фотографы Севера', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Никитина', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISSN 0202-2400', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'вып. 2', 'class': 'optional'}),
                   "doi": TextInput(attrs={'placeholder': '10.1596/978-0-8213-6475-8', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "key_title": TextInput(attrs={'placeholder': 'Фотография', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Щербаков', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'И. Л.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'сайт', 'class': 'optional'}),
                   "url": TextInput(attrs={'placeholder': 'http://www.photographers.ru/newspaper/', 'class': 'required'}),
                   "application_date": TextInput(attrs={'placeholder': '25.04.2021'})}


class GostForm(ModelForm):
    class Meta:
        model = Gost
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'ГОСТ Р 52196 – 2003. Изделия колбасные вареные. Технические условия', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2004', 'class': 'required'}),
                   "date": TextInput(attrs={'placeholder': '2003-12-29', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '26', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Изд-во стандартов', 'class': 'required'}),
                   "introduction": TextInput(attrs={'placeholder': 'введ. впервые', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'текст', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional', 'type': 'hidden'})}

class SiteArticleForm(ModelForm):
    class Meta:
        model = SiteArticle
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Процесс социализации', 'class': 'required'}),
                   "site_title": TextInput(attrs={'placeholder': 'Основы обществознания', 'class': 'required'}),
                   "url": TextInput(attrs={'placeholder': 'https://social-sciences.ru/protsess-sotsializatsii', 'class': 'required'})}


class DissertationForm(ModelForm):
    class Meta:
        model = Dissertation
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Публичная библиотека в системе непрерывного библиотечноинформационного образования', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Аврамова', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'Е. В.', 'class': 'required'}),
                   "full_name": TextInput(attrs={'placeholder': 'Елена Викторовна', 'class': 'required'}),
                   "speciality": TextInput(attrs={'placeholder': '05.25.03 «Библиотековедение, библиографоведение и книговедение»', 'class': 'required'}),
                   "competition": TextInput(attrs={'placeholder': 'ученой степени кандидата педагогических наук', 'class': 'required'}),
                   "bibliography": TextInput(attrs={'placeholder': '296–335', 'class': 'optional'}),
                   "place": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2017', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '361', 'class': 'required'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '5', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "organization": TextInput(attrs={'placeholder': 'Санкт-Петербургский государственный институт культуры', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'диссертация', 'class': 'optional', 'type': 'hidden'})}


class DissertationAbstractForm(ModelForm):
    class Meta:
        model = DissertationAbstract
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Функциональная организация рабочей памяти', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Величковский', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'Б. Б.', 'class': 'required'}),
                   "full_name": TextInput(attrs={'placeholder': 'Борис Борисович', 'class': 'required'}),
                   "speciality": TextInput(attrs={'placeholder': '19.00.01 «Общая психология, психология личности, история психологии»', 'class': 'required'}),
                   "competition": TextInput(attrs={'placeholder': 'ученой степени кандидата педагогических наук', 'class': 'required'}),
                   "bibliography": TextInput(attrs={'placeholder': '37–44', 'class': 'optional'}),
                   "place": TextInput(attrs={'placeholder': 'Москва', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2017', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '44', 'class': 'required'}),
                   "protection": TextInput(attrs={'placeholder': 'Ин-т психологии РАН', 'class': 'required'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '5', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "organization": TextInput(attrs={'placeholder': 'Московский государственный университет им. М. В. Ломоносова', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'автореферат диссертации', 'class': 'optional', 'type': 'hidden'})}


class ManualForm(ModelForm):
    class Meta:
        model = Manual
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Классика и современная литература: почитаем и подумаем вместе', 'class': 'required'}),
                   "manual_type": TextInput(attrs={'placeholder': 'учебно-методическое', 'class': 'required'}),
                   "surname": TextInput(attrs={'placeholder': 'Колтухова', 'class': 'required'}),
                   "initials": TextInput(attrs={'placeholder': 'И. М.', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Симферополь', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Ариал', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2017', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '151', 'class': 'required'}),
                   "bibliography": TextInput(attrs={'placeholder': '149–151', 'class': 'optional'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-906962-43-0', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Classics and modern literature', 'class': 'optional'}),
                   "responsibility": TextInput(attrs={'placeholder': 'Министерство образования и науки Российской Федерации', 'class': 'optional'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2021', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '21', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': '1 плакат', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '100 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "availability": TextInput(attrs={'placeholder': 'беспл. для студентов ин-та', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "second_surname": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "fourth_surname": TextInput(attrs={'placeholder': 'Щербаков', 'class': 'optional_author'}),
                   "fourth_initials": TextInput(attrs={'placeholder': 'И. Л.', 'class': 'optional_author'}),
                   "second_surname_2": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_2": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_3": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_3": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "second_surname_4": TextInput(attrs={'placeholder': 'Кузнецов', 'class': 'optional_author'}),
                   "second_initials_4": TextInput(attrs={'placeholder': 'О. Л.', 'class': 'optional_author'}),
                   "third_surname_2": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_2": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "third_surname_3": TextInput(attrs={'placeholder': 'Мартынова', 'class': 'optional_author'}),
                   "third_initials_3": TextInput(attrs={'placeholder': 'Ф. Н.', 'class': 'optional_author'}),
                   "explanations": TextInput(attrs={'placeholder': 'по направлению подготовки 45.03.01 «Филология» (русский язык и литература)', 'class': 'optional', 'type': 'hidden'})}


class LawForm(ModelForm):
    class Meta:
        model = Law
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Об информации, информационных технологиях и о защите информации', 'class': 'required'}),
                   "organization": TextInput(attrs={'placeholder': 'Федеральный закон от 27 июля 2006 г. № 149-ФЗ ', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Собрание законодательства Российской Федерации', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': '31, ч. 1', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2006', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '3448', 'class': 'required'})}


class RuleForm(ModelForm):
    class Meta:
        model = Rule
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Правила дорожного движения', 'class': 'required'}),
                   "place": TextInput(attrs={'placeholder': 'Ростов-на-Дону', 'class': 'required'}),
                   "publishing": TextInput(attrs={'placeholder': 'Феникс', 'class': 'required'}),
                   "year": TextInput(attrs={'placeholder': '2017', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '94', 'class': 'required'}),
                   "isbn": TextInput(attrs={'placeholder': '978-5-222-29588-5', 'class': 'required'}),
                   "parallel": TextInput(attrs={'placeholder': 'Traffic Laws', 'class': 'optional'}),
                   "type_doc": TextInput(attrs={'placeholder': 'с новыми штрафами : по состоянию на 01.06.2017', 'class': 'optional'}),
                   "liability": TextInput(attrs={'placeholder': 'дополнил с 1-го издания П. Агафошин', 'class': 'optional'}),
                   "place_of_distribution": TextInput(attrs={'placeholder': 'Санкт-Петербург', 'class': 'optional'}),
                   "organization_of_distribution": TextInput(attrs={'placeholder': 'Медиа-Групп', 'class': 'optional'}),
                   "distribution_date": TextInput(attrs={'placeholder': '2018', 'class': 'optional'}),
                   "manufacture": TextInput(attrs={'placeholder': 'Москва : Эксперим. тип.', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '20', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': '1 плакат', 'class': 'optional'}),
                   "main_title": TextInput(attrs={'placeholder': 'Библиотека автомобилиста', 'class': 'optional'}),
                   "parallel_series_title": TextInput(attrs={'placeholder': 'Current legislation', 'class': 'optional'}),
                   "series_title_information": TextInput(attrs={'placeholder': 'правила дорожного движения', 'class': 'optional'}),
                   "responsibility_info": TextInput(attrs={'placeholder': 'под общей редакцией И. Н. Петрова', 'class': 'optional'}),
                   "number": TextInput(attrs={'placeholder': 'ISBN 978-5-7310-3503-3', 'class': 'optional'}),
                   "serial_number": TextInput(attrs={'placeholder': 'т. 4', 'class': 'optional'}),
                   "sub_main_title": TextInput(attrs={'placeholder': 'Серия 1', 'class': 'optional'}),
                   "sub_parallel_series_title": TextInput(attrs={'placeholder': 'Series 1', 'class': 'optional'}),
                   "sub_series_title_information": TextInput(attrs={'placeholder': 'правила', 'class': 'optional'}),
                   "sub_responsibility_info": TextInput(attrs={'placeholder': 'под редакцией Л. К. Иванова', 'class': 'optional'}),
                   "sub_number": TextInput(attrs={'placeholder': 'ISBN 978-5-699-12014-7', 'class': 'optional'}),
                   "sub_serial_number": TextInput(attrs={'placeholder': 'ч. 2', 'class': 'optional'}),
                   "notes": TextInput(attrs={'placeholder': 'Авт. указаны на 7-й странице', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '1000 экз.', 'class': 'optional'}),
                   "additional_information": TextInput(attrs={'placeholder': 'вкладыш', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'утверждены Советом министров – Правительством Российской Федерации 23.10.1993', 'class': 'optional'}),
                   "edit_info": TextInput(attrs={'placeholder': 'Дополненный вариант', 'class': 'required'}),
                   "par_edit_info": TextInput(attrs={'placeholder': 'augmented version', 'class': 'optional', 'type': 'hidden'})}


class PatentForm(ModelForm):
    class Meta:
        model = Patent
        fields = '__all__'
        widgets = {"title": TextInput(attrs={'placeholder': 'Приемопередающее устройство', 'class': 'required'}),
                   "info": TextInput(attrs={'placeholder': '2187888 Российская Федерация, МПК Н 04 В 1/38, Н 04 J 13/00.', 'class': 'required'}),
                   "number": TextInput(attrs={'placeholder': '2000131736/09', 'class': 'required'}),
                   "application": TextInput(attrs={'placeholder': '18.12.2000', 'class': 'required'}),
                   "publication": TextInput(attrs={'placeholder': '20.08.2002', 'class': 'required'}),
                   "author": TextInput(attrs={'placeholder': 'Артеменко К. И., Богданов Н. Э.', 'class': 'required'}),
                   "pages": TextInput(attrs={'placeholder': '3', 'class': 'required'}),
                   "responsibility": TextInput(attrs={'placeholder': 'заявитель и патентообладатель Воронеж. науч.-исслед. ин-т связи', 'class': 'optional'}),
                   "unnumbered_pages": TextInput(attrs={'placeholder': '8', 'class': 'optional'}),
                   "illustrations": TextInput(attrs={'placeholder': '[4] л.', 'class': 'optional'}),
                   "physical_characteristics": TextInput(attrs={'placeholder': 'ил.', 'class': 'optional'}),
                   "size": TextInput(attrs={'placeholder': '20', 'class': 'optional'}),
                   "accompanying": TextInput(attrs={'placeholder': '1 плакат', 'class': 'optional'}),
                   "general_notes": TextInput(attrs={'placeholder': '1 экз.', 'class': 'optional'}),
                   "content": TextInput(attrs={'placeholder': 'Текст', 'class': 'optional'}),
                   "content_type": TextInput(attrs={'placeholder': 'визуальный', 'class': 'optional'}),
                   "access_means": TextInput(attrs={'placeholder': 'непосредственный', 'class': 'optional'}),
                   "explanations": TextInput(attrs={'placeholder': 'патент', 'class': 'optional', 'type': 'hidden'})}